{% set version = "8.0.0" %}
{% set sha256 = "49918b9f09816554a20ac44c5f85a32dc0a7a00759b3259e78064d674eac0373" %}

package:
  name: lldb
  version: {{ version }}

source:
  url: http://releases.llvm.org/{{ version }}/lldb-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}
  patches:
    # Remove use of private header in LLDB
    # ref https://reviews.llvm.org/D41824
    - D41824.patch
    # This is fixed in next release
    - compression.h.patch

build:
  number: 0
  skip: true  # [win and py<35]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.4.3
    - ninja    # [win]
  host:
    - python
    - llvmdev =={{ version }}
    - clangdev =={{ version }}
    - swig
    - libedit  # [linux]
  run:
    - libedit  # [linux]
    - python
  run_constrained:
    - llvmdev =={{ version }}
    - clangdev =={{ version }}

test:
  commands:
    - lldb --version

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: The LLVM Debugger

extra:
  recipe-maintainers:
    - inducer
    - isuruf
