{% set version = "9.0.1" %}
{% set sha256 = "8a7b9fd795c31a3e3cba6ce1377a2ae5c67376d92888702ce27e26f0971beb09" %}

package:
  name: lldb
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version }}/lldb-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}
  patches:
    # Remove use of private header in LLDB
    # ref https://reviews.llvm.org/D41824
    - D41824.patch
    # This is fixed in next release
    - compression.h.patch

build:
  number: 0
  skip: true  # [win and py<35]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.4.3
    - ninja    # [win]
  host:
    - python
    - llvmdev =={{ version }}
    - clangdev =={{ version }}
    - swig
    - libedit  # [linux]
  run:
    - libedit  # [linux]
    - python
  run_constrained:
    - llvmdev =={{ version }}
    - clangdev =={{ version }}

test:
  commands:
    - lldb --version

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: The LLVM Debugger

extra:
  recipe-maintainers:
    - inducer
    - isuruf
