{% set version = "6.0.0" %}
{% set sha256 = "46f54c1d7adcd047d87c0179f7b6fa751614f339f4f87e60abceaa45f414d454" %}

package:
  name: lldb
  version: {{ version }}

source:
  fn: lldb-{{ version }}.src.tar.xz
  url: http://releases.llvm.org/{{ version }}/lldb-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}
  patches:
    - build_external.patch

build:
  number: 0
  skip: true  # [win and py<35]
  features:
    - vc14    # [win and py>=35]

requirements:
  build:
    - toolchain
    - cmake >=3.4.3
    - ninja    # [win]
    - python
    - llvmdev =={{ version }}
    - clangdev =={{ version }}
    - libxml2 2.9.*
    - swig
    - libedit  # [linux]
    - vc 14    # [win]
    - libcxx   # [osx]
  run:
    - libedit  # [linux]
    - vc 14    # [win]
    - libcxx   # [osx]
    - llvmdev =={{ version }}
    - clangdev =={{ version }}
    - python

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}  # [win]
    - cmake >=3.4.3

  commands:
    - lldb --version

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: The LLVM Debugger

extra:
  recipe-maintainers:
    - inducer
    - isuruf
