travis:
  secure:
    BINSTAR_TOKEN: iAO3Ey7K60f2jWPEHMyfUDeLiUf8MHGMG1bBU7elh9GuU3DJ2VZv2B2KlSFyuokS+yq60vPIDg2YvBGJAYkhppj+n4n9XwuhqUEkJmaOTP3uug9ReqVCRd7K4h4PPbLSM26SEEmwEO/oyu5vRzmxVIswKfwP9SMsrQ0m0lQ09j4EL1h8rNjKLJIT45MBs3FOiCPtnSsc1vVtdqVVyr25QRUN22QvVUzLguB1W+XtCQUtZwdHkRvlZBEXztJXy8wc4oY1vOAUSgg2vBsk6hFdmzero2VyW4ZpI4b5MlrRsx6qJlKGpYOGbhT+bIuBVE9ypr/SSL3gdjZxij5zjT8JZ41+jebo7NB11yoyzXVEyEYoIDNA4BmvB0PLFjznd5+/2BYBY8awy7r4+KlNlgh6CGiIgq3MJoiGSJ4L1UjjeFBO+9xr1HNgC0R5hqYRBBKDvV8eVx2ErehAXtAe9PeRLsdEwxi9jMj4m963S6YDSdtL9eJxF3AZLgmMnmMk7nJ+6D9/sN+m+oFVd61Oj6RA1eKagp/c5b9Ez864eRywDXwlkihgLfV57vFkmBNBgxMH+dPYMcHwTYMsIFKXOvY+H63EEY0g4NlQtfg+pZbFzgXVeUpBi/ch4/HBM/gMRXSjlsll1Rw5mOmhlXfYremLN304PcyGR/KUsr/5jwRLhbM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
